### ISSUE TITLE
Remove this plugin.

### ISSUE THREAD

**Issue by hingston** [pkunk/intellij-hoi4#2]
Why am I getting this as a suggestion for all .txt files in PyCharm?

**Comment by deividaspetraitis** [comment]
Same for PhpStorm.

**Comment by EskoCruz** [comment]
Just got this suggestion myself for IntelliJ IDEA to handle .txt files.
Why whould I use this plugin and what are any benifits.
Seams very suspicious!

**Comment by mikhailvink** [comment]
We have disabled *.txt file suggestions "implemented" by the plugin yesterday on JetBrains Plugins Repository side.

**Comment by pkunk** [comment]
@mikhailvink thanks!
